<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\WordDictionary;
use Illuminate\Support\Facades\Schema;

class InitialDataSeeder extends Seeder
{
    public function run(): void
    {
        // Matikan proteksi foreign key khusus SQLite lek
        Schema::disableForeignKeyConstraints();
        
        Country::truncate();
        WordDictionary::truncate();
        
        Schema::enableForeignKeyConstraints();

        // 1. Array Data 250+ Negara Lengkap (Nama, ISO2, Kode Mata Uang, Estimasi Koordinat)
        $countries = [
            ['name' => 'Andorra', 'code_iso2' => 'AD', 'currency_code' => 'EUR', 'latitude' => 42.5063, 'longitude' => 1.5218],
            ['name' => 'United Arab Emirates', 'code_iso2' => 'AE', 'currency_code' => 'AED', 'latitude' => 23.4241, 'longitude' => 53.8478],
            ['name' => 'Afghanistan', 'code_iso2' => 'AF', 'currency_code' => 'AFN', 'latitude' => 33.9391, 'longitude' => 67.7100],
            ['name' => 'Antigua and Barbuda', 'code_iso2' => 'AG', 'currency_code' => 'XCD', 'latitude' => 17.0608, 'longitude' => -61.7964],
            ['name' => 'Anguilla', 'code_iso2' => 'AI', 'currency_code' => 'XCD', 'latitude' => 18.2206, 'longitude' => -63.0686],
            ['name' => 'Albania', 'code_iso2' => 'AL', 'currency_code' => 'ALL', 'latitude' => 41.1533, 'longitude' => 20.1683],
            ['name' => 'Armenia', 'code_iso2' => 'AM', 'currency_code' => 'AMD', 'latitude' => 40.0691, 'longitude' => 45.0382],
            ['name' => 'Angola', 'code_iso2' => 'AO', 'currency_code' => 'AOA', 'latitude' => -11.2027, 'longitude' => 17.8739],
            ['name' => 'Argentina', 'code_iso2' => 'AR', 'currency_code' => 'ARS', 'latitude' => -38.4161, 'longitude' => -63.6167],
            ['name' => 'American Samoa', 'code_iso2' => 'AS', 'currency_code' => 'USD', 'latitude' => -14.2710, 'longitude' => -170.1322],
            ['name' => 'Austria', 'code_iso2' => 'AT', 'currency_code' => 'EUR', 'latitude' => 47.5162, 'longitude' => 14.5501],
            ['name' => 'Australia', 'code_iso2' => 'AU', 'currency_code' => 'AUD', 'latitude' => -25.2744, 'longitude' => 133.7751],
            ['name' => 'Aruba', 'code_iso2' => 'AW', 'currency_code' => 'AWG', 'latitude' => 12.5211, 'longitude' => -69.9683],
            ['name' => 'Aland Islands', 'code_iso2' => 'AX', 'currency_code' => 'EUR', 'latitude' => 60.1785, 'longitude' => 19.9156],
            ['name' => 'Azerbaijan', 'code_iso2' => 'AZ', 'currency_code' => 'AZN', 'latitude' => 40.1431, 'longitude' => 47.5769],
            ['name' => 'Bosnia and Herzegovina', 'code_iso2' => 'BA', 'currency_code' => 'BAM', 'latitude' => 43.9159, 'longitude' => 17.6791],
            ['name' => 'Barbados', 'code_iso2' => 'BB', 'currency_code' => 'BBD', 'latitude' => 13.1939, 'longitude' => -59.5432],
            ['name' => 'Bangladesh', 'code_iso2' => 'BD', 'currency_code' => 'BDT', 'latitude' => 23.6850, 'longitude' => 90.3563],
            ['name' => 'Belgium', 'code_iso2' => 'BE', 'currency_code' => 'EUR', 'latitude' => 50.5039, 'longitude' => 4.4699],
            ['name' => 'Burkina Faso', 'code_iso2' => 'BF', 'currency_code' => 'XOF', 'latitude' => 12.2383, 'longitude' => -1.5616],
            ['name' => 'Bulgaria', 'code_iso2' => 'BG', 'currency_code' => 'BGN', 'latitude' => 42.7339, 'longitude' => 25.4858],
            ['name' => 'Bahrain', 'code_iso2' => 'BH', 'currency_code' => 'BHD', 'latitude' => 25.9304, 'longitude' => 50.6377],
            ['name' => 'Burundi', 'code_iso2' => 'BI', 'currency_code' => 'BIF', 'latitude' => -3.3731, 'longitude' => 29.9189],
            ['name' => 'Benin', 'code_iso2' => 'BJ', 'currency_code' => 'XOF', 'latitude' => 9.3077, 'longitude' => 2.3158],
            ['name' => 'Saint Barthelemy', 'code_iso2' => 'BL', 'currency_code' => 'EUR', 'latitude' => 17.9000, 'longitude' => -62.8333],
            ['name' => 'Bermuda', 'code_iso2' => 'BM', 'currency_code' => 'BMD', 'latitude' => 32.3214, 'longitude' => -64.7574],
            ['name' => 'Brunei', 'code_iso2' => 'BN', 'currency_code' => 'BND', 'latitude' => 4.5353, 'longitude' => 114.7277],
            ['name' => 'Bolivia', 'code_iso2' => 'BO', 'currency_code' => 'BOB', 'latitude' => -16.2902, 'longitude' => -63.5887],
            ['name' => 'Bonaire', 'code_iso2' => 'BQ', 'currency_code' => 'USD', 'latitude' => 12.1784, 'longitude' => -68.2385],
            ['name' => 'Brazil', 'code_iso2' => 'BR', 'currency_code' => 'BRL', 'latitude' => -14.2350, 'longitude' => -51.9253],
            ['name' => 'Bahamas', 'code_iso2' => 'BS', 'currency_code' => 'BSD', 'latitude' => 25.0343, 'longitude' => -77.3963],
            ['name' => 'Bhutan', 'code_iso2' => 'BT', 'currency_code' => 'BTN', 'latitude' => 27.5142, 'longitude' => 90.4336],
            ['name' => 'Bouvet Island', 'code_iso2' => 'BV', 'currency_code' => 'NOK', 'latitude' => -54.4208, 'longitude' => 3.3464],
            ['name' => 'Botswana', 'code_iso2' => 'BW', 'currency_code' => 'BWP', 'latitude' => -22.3285, 'longitude' => 24.6849],
            ['name' => 'Belarus', 'code_iso2' => 'BY', 'currency_code' => 'BYN', 'latitude' => 53.7098, 'longitude' => 27.9534],
            ['name' => 'Belize', 'code_iso2' => 'BZ', 'currency_code' => 'BZD', 'latitude' => 17.1899, 'longitude' => -88.4976],
            ['name' => 'Canada', 'code_iso2' => 'CA', 'currency_code' => 'CAD', 'latitude' => 56.1304, 'longitude' => -106.3468],
            ['name' => 'Cocos Islands', 'code_iso2' => 'CC', 'currency_code' => 'AUD', 'latitude' => -12.1642, 'longitude' => 96.8710],
            ['name' => 'Democratic Republic of the Congo', 'code_iso2' => 'CD', 'currency_code' => 'CDF', 'latitude' => -4.0383, 'longitude' => 21.7587],
            ['name' => 'Central African Republic', 'code_iso2' => 'CF', 'currency_code' => 'XAF', 'latitude' => 6.6111, 'longitude' => 20.9394],
            ['name' => 'Republic of the Congo', 'code_iso2' => 'CG', 'currency_code' => 'XAF', 'latitude' => -0.2280, 'longitude' => 15.8277],
            ['name' => 'Switzerland', 'code_iso2' => 'CH', 'currency_code' => 'CHF', 'latitude' => 46.8182, 'longitude' => 8.2275],
            ['name' => 'Ivory Coast', 'code_iso2' => 'CI', 'currency_code' => 'XOF', 'latitude' => 7.5400, 'longitude' => -5.5471],
            ['name' => 'Cook Islands', 'code_iso2' => 'CK', 'currency_code' => 'NZD', 'latitude' => -21.2367, 'longitude' => -159.7777],
            ['name' => 'Chile', 'code_iso2' => 'CL', 'currency_code' => 'CLP', 'latitude' => -35.6751, 'longitude' => -71.5430],
            ['name' => 'Cameroon', 'code_iso2' => 'CM', 'currency_code' => 'XAF', 'latitude' => 7.3697, 'longitude' => 12.3547],
            ['name' => 'China', 'code_iso2' => 'CN', 'currency_code' => 'CNY', 'latitude' => 35.8617, 'longitude' => 104.1954],
            ['name' => 'Colombia', 'code_iso2' => 'CO', 'currency_code' => 'COP', 'latitude' => 4.5709, 'longitude' => -74.2973],
            ['name' => 'Costa Rica', 'code_iso2' => 'CR', 'currency_code' => 'CRC', 'latitude' => 9.7489, 'longitude' => -83.7534],
            ['name' => 'Cuba', 'code_iso2' => 'CU', 'currency_code' => 'CUP', 'latitude' => 21.5218, 'longitude' => -77.7812],
            ['name' => 'Cape Verde', 'code_iso2' => 'CV', 'currency_code' => 'CVE', 'latitude' => 16.0021, 'longitude' => -24.0132],
            ['name' => 'Curacao', 'code_iso2' => 'CW', 'currency_code' => 'ANG', 'latitude' => 12.1696, 'longitude' => -68.9900],
            ['name' => 'Christmas Island', 'code_iso2' => 'CX', 'currency_code' => 'AUD', 'latitude' => -10.4475, 'longitude' => 105.6904],
            ['name' => 'Cyprus', 'code_iso2' => 'CY', 'currency_code' => 'EUR', 'latitude' => 35.1264, 'longitude' => 33.4299],
            ['name' => 'Czech Republic', 'code_iso2' => 'CZ', 'currency_code' => 'CZK', 'latitude' => 49.8175, 'longitude' => 15.4730],
            ['name' => 'Germany', 'code_iso2' => 'DE', 'currency_code' => 'EUR', 'latitude' => 51.1657, 'longitude' => 10.4515],
            ['name' => 'Djibouti', 'code_iso2' => 'DJ', 'currency_code' => 'DJF', 'latitude' => 11.8251, 'longitude' => 42.5903],
            ['name' => 'Denmark', 'code_iso2' => 'DK', 'currency_code' => 'DKK', 'latitude' => 56.2639, 'longitude' => 9.5018],
            ['name' => 'Dominica', 'code_iso2' => 'DM', 'currency_code' => 'XCD', 'latitude' => 15.4149, 'longitude' => -61.3705],
            ['name' => 'Dominican Republic', 'code_iso2' => 'DO', 'currency_code' => 'DOP', 'latitude' => 18.7357, 'longitude' => -70.1627],
            ['name' => 'Algeria', 'code_iso2' => 'DZ', 'currency_code' => 'DZD', 'latitude' => 28.0339, 'longitude' => 1.6596],
            ['name' => 'Ecuador', 'code_iso2' => 'EC', 'currency_code' => 'USD', 'latitude' => -1.8312, 'longitude' => -78.1834],
            ['name' => 'Estonia', 'code_iso2' => 'EE', 'currency_code' => 'EUR', 'latitude' => 58.5953, 'longitude' => 25.0136],
            ['name' => 'Egypt', 'code_iso2' => 'EG', 'currency_code' => 'EGP', 'latitude' => 26.8206, 'longitude' => 30.8025],
            ['name' => 'Western Sahara', 'code_iso2' => 'EH', 'currency_code' => 'MAD', 'latitude' => 24.2155, 'longitude' => -12.8858],
            ['name' => 'Eritrea', 'code_iso2' => 'ER', 'currency_code' => 'ERN', 'latitude' => 15.1794, 'longitude' => 39.7823],
            ['name' => 'Spain', 'code_iso2' => 'ES', 'currency_code' => 'EUR', 'latitude' => 40.4637, 'longitude' => -3.7492],
            ['name' => 'Ethiopia', 'code_iso2' => 'ET', 'currency_code' => 'ETB', 'latitude' => 9.1450, 'longitude' => 40.4897],
            ['name' => 'Finland', 'code_iso2' => 'FI', 'currency_code' => 'EUR', 'latitude' => 61.9241, 'longitude' => 25.7482],
            ['name' => 'Fiji', 'code_iso2' => 'FJ', 'currency_code' => 'FJD', 'latitude' => -16.5782, 'longitude' => 179.4144],
            ['name' => 'Falkland Islands', 'code_iso2' => 'FK', 'currency_code' => 'FKP', 'latitude' => -51.7963, 'longitude' => -59.5236],
            ['name' => 'Micronesia', 'code_iso2' => 'FM', 'currency_code' => 'USD', 'latitude' => 7.4256, 'longitude' => 150.5508],
            ['name' => 'Faroe Islands', 'code_iso2' => 'FO', 'currency_code' => 'DKK', 'latitude' => 62.0079, 'longitude' => -6.7808],
            ['name' => 'France', 'code_iso2' => 'FR', 'currency_code' => 'EUR', 'latitude' => 46.2276, 'longitude' => 2.2137],
            ['name' => 'Gabon', 'code_iso2' => 'GA', 'currency_code' => 'XAF', 'latitude' => -0.8037, 'longitude' => 11.6094],
            ['name' => 'United Kingdom', 'code_iso2' => 'GB', 'currency_code' => 'GBP', 'latitude' => 55.3781, 'longitude' => -3.4360],
            ['name' => 'Grenada', 'code_iso2' => 'GD', 'currency_code' => 'XCD', 'latitude' => 12.2628, 'longitude' => -61.6042],
            ['name' => 'Georgia', 'code_iso2' => 'GE', 'currency_code' => 'GEL', 'latitude' => 42.3154, 'longitude' => 43.3569],
            ['name' => 'French Guiana', 'code_iso2' => 'GF', 'currency_code' => 'EUR', 'latitude' => 3.9339, 'longitude' => -53.1258],
            ['name' => 'Guernsey', 'code_iso2' => 'GG', 'currency_code' => 'GBP', 'latitude' => 49.4657, 'longitude' => -2.5853],
            ['name' => 'Ghana', 'code_iso2' => 'GH', 'currency_code' => 'GHS', 'latitude' => 7.9465, 'longitude' => -1.0232],
            ['name' => 'Gibraltar', 'code_iso2' => 'GI', 'currency_code' => 'GIP', 'latitude' => 36.1408, 'longitude' => -5.3536],
            ['name' => 'Greenland', 'code_iso2' => 'GL', 'currency_code' => 'DKK', 'latitude' => 71.7069, 'longitude' => -42.6043],
            ['name' => 'Gambia', 'code_iso2' => 'GM', 'currency_code' => 'GMD', 'latitude' => 13.4432, 'longitude' => -15.3101],
            ['name' => 'Guinea', 'code_iso2' => 'GN', 'currency_code' => 'GNF', 'latitude' => 9.9456, 'longitude' => -9.6966],
            ['name' => 'Guadeloupe', 'code_iso2' => 'GP', 'currency_code' => 'EUR', 'latitude' => 16.9960, 'longitude' => -62.0677],
            ['name' => 'Equatorial Guinea', 'code_iso2' => 'GQ', 'currency_code' => 'XAF', 'latitude' => 1.6508, 'longitude' => 10.2679],
            ['name' => 'Greece', 'code_iso2' => 'GR', 'currency_code' => 'EUR', 'latitude' => 39.0742, 'longitude' => 21.8243],
            ['name' => 'South Georgia', 'code_iso2' => 'GS', 'currency_code' => 'GBP', 'latitude' => -54.4296, 'longitude' => -36.5879],
            ['name' => 'Guatemala', 'code_iso2' => 'GT', 'currency_code' => 'GTQ', 'latitude' => 15.7835, 'longitude' => -90.2308],
            ['name' => 'Guam', 'code_iso2' => 'GU', 'currency_code' => 'USD', 'latitude' => 13.4443, 'longitude' => 144.7937],
            ['name' => 'Guinea-Bissau', 'code_iso2' => 'GW', 'currency_code' => 'XOF', 'latitude' => 11.8037, 'longitude' => -15.1804],
            ['name' => 'Guyana', 'code_iso2' => 'GY', 'currency_code' => 'GYD', 'latitude' => 4.8604, 'longitude' => -58.9302],
            ['name' => 'Hong Kong', 'code_iso2' => 'HK', 'currency_code' => 'HKD', 'latitude' => 22.3964, 'longitude' => 114.1095],
            ['name' => 'Heard Island', 'code_iso2' => 'HM', 'currency_code' => 'AUD', 'latitude' => -53.0818, 'longitude' => 73.5042],
            ['name' => 'Honduras', 'code_iso2' => 'HN', 'currency_code' => 'HNL', 'latitude' => 15.2000, 'longitude' => -86.2419],
            ['name' => 'Croatia', 'code_iso2' => 'HR', 'currency_code' => 'EUR', 'latitude' => 45.1000, 'longitude' => 15.2000],
            ['name' => 'Haiti', 'code_iso2' => 'HT', 'currency_code' => 'HTG', 'latitude' => 18.9712, 'longitude' => -72.2852],
            ['name' => 'Hungary', 'code_iso2' => 'HU', 'currency_code' => 'HUF', 'latitude' => 47.1625, 'longitude' => 19.5033],
            ['name' => 'Indonesia', 'code_iso2' => 'ID', 'currency_code' => 'IDR', 'latitude' => -0.7893, 'longitude' => 113.9213],
            ['name' => 'Ireland', 'code_iso2' => 'IE', 'currency_code' => 'EUR', 'latitude' => 53.4129, 'longitude' => -8.2439],
            ['name' => 'Israel', 'code_iso2' => 'IL', 'currency_code' => 'ILS', 'latitude' => 31.0461, 'longitude' => 34.8516],
            ['name' => 'Isle of Man', 'code_iso2' => 'IM', 'currency_code' => 'GBP', 'latitude' => 54.2361, 'longitude' => -4.5481],
            ['name' => 'India', 'code_iso2' => 'IN', 'currency_code' => 'INR', 'latitude' => 20.5937, 'longitude' => 78.9629],
            ['name' => 'British Indian Ocean Territory', 'code_iso2' => 'IO', 'currency_code' => 'USD', 'latitude' => -6.3431, 'longitude' => 71.8765],
            ['name' => 'Iraq', 'code_iso2' => 'IQ', 'currency_code' => 'IQD', 'latitude' => 33.2232, 'longitude' => 43.6793],
            ['name' => 'Iran', 'code_iso2' => 'IR', 'currency_code' => 'IRR', 'latitude' => 32.4279, 'longitude' => 53.6880],
            ['name' => 'Iceland', 'code_iso2' => 'IS', 'currency_code' => 'ISK', 'latitude' => 64.9631, 'longitude' => -19.0208],
            ['name' => 'Italy', 'code_iso2' => 'IT', 'currency_code' => 'EUR', 'latitude' => 41.8719, 'longitude' => 12.5674],
            ['name' => 'Jersey', 'code_iso2' => 'JE', 'currency_code' => 'GBP', 'latitude' => 49.2144, 'longitude' => -2.1312],
            ['name' => 'Jamaica', 'code_iso2' => 'JM', 'currency_code' => 'JMD', 'latitude' => 18.1096, 'longitude' => -77.2975],
            ['name' => 'Jordan', 'code_iso2' => 'JO', 'currency_code' => 'JOD', 'latitude' => 30.5852, 'longitude' => 36.2384],
            ['name' => 'Japan', 'code_iso2' => 'JP', 'currency_code' => 'JPY', 'latitude' => 36.2048, 'longitude' => 138.2529],
            ['name' => 'Kenya', 'code_iso2' => 'KE', 'currency_code' => 'KES', 'latitude' => -0.0236, 'longitude' => 37.9062],
            ['name' => 'Kyrgyzstan', 'code_iso2' => 'KG', 'currency_code' => 'KGS', 'latitude' => 41.2044, 'longitude' => 74.7661],
            ['name' => 'Cambodia', 'code_iso2' => 'KH', 'currency_code' => 'KHR', 'latitude' => 12.5657, 'longitude' => 104.9910],
            ['name' => 'Kiribati', 'code_iso2' => 'KI', 'currency_code' => 'AUD', 'latitude' => -3.3704, 'longitude' => -168.7340],
            ['name' => 'Comoros', 'code_iso2' => 'KM', 'currency_code' => 'KMF', 'latitude' => -11.8750, 'longitude' => 43.8722],
            ['name' => 'Saint Kitts and Nevis', 'code_iso2' => 'KN', 'currency_code' => 'XCD', 'latitude' => 17.3578, 'longitude' => -62.7830],
            ['name' => 'North Korea', 'code_iso2' => 'KP', 'currency_code' => 'KPW', 'latitude' => 40.3399, 'longitude' => 127.5101],
            ['name' => 'South Korea', 'code_iso2' => 'KR', 'currency_code' => 'KRW', 'latitude' => 35.9078, 'longitude' => 127.7669],
            ['name' => 'Kuwait', 'code_iso2' => 'KW', 'currency_code' => 'KWD', 'latitude' => 29.3117, 'longitude' => 47.4818],
            ['name' => 'Cayman Islands', 'code_iso2' => 'KY', 'currency_code' => 'KYD', 'latitude' => 19.5135, 'longitude' => -80.5670],
            ['name' => 'Kazakhstan', 'code_iso2' => 'KZ', 'currency_code' => 'KZT', 'latitude' => 48.0196, 'longitude' => 66.9237],
            ['name' => 'Laos', 'code_iso2' => 'LA', 'currency_code' => 'LAK', 'latitude' => 19.8563, 'longitude' => 102.4955],
            ['name' => 'Lebanon', 'code_iso2' => 'LB', 'currency_code' => 'LBP', 'latitude' => 33.8547, 'longitude' => 35.8623],
            ['name' => 'Saint Lucia', 'code_iso2' => 'LC', 'currency_code' => 'XCD', 'latitude' => 13.9094, 'longitude' => -60.9789],
            ['name' => 'Liechtenstein', 'code_iso2' => 'LI', 'currency_code' => 'CHF', 'latitude' => 47.1660, 'longitude' => 9.5554],
            ['name' => 'Sri Lanka', 'code_iso2' => 'LK', 'currency_code' => 'LKR', 'latitude' => 7.8731, 'longitude' => 80.7718],
            ['name' => 'Liberia', 'code_iso2' => 'LR', 'currency_code' => 'LRD', 'latitude' => 6.4281, 'longitude' => -9.4295],
            ['name' => 'Lesotho', 'code_iso2' => 'LS', 'currency_code' => 'LSL', 'latitude' => -29.6100, 'longitude' => 28.2336],
            ['name' => 'Lithuania', 'code_iso2' => 'LT', 'currency_code' => 'EUR', 'latitude' => 55.1694, 'longitude' => 23.8813],
            ['name' => 'Luxembourg', 'code_iso2' => 'LU', 'currency_code' => 'EUR', 'latitude' => 49.8153, 'longitude' => 6.1296],
            ['name' => 'Latvia', 'code_iso2' => 'LV', 'currency_code' => 'EUR', 'latitude' => 56.8796, 'longitude' => 24.6032],
            ['name' => 'Libya', 'code_iso2' => 'LY', 'currency_code' => 'LYD', 'latitude' => 26.3351, 'longitude' => 17.2283],
            ['name' => 'Morocco', 'code_iso2' => 'MA', 'currency_code' => 'MAD', 'latitude' => 31.7917, 'longitude' => -7.0926],
            ['name' => 'Monaco', 'code_iso2' => 'MC', 'currency_code' => 'EUR', 'latitude' => 43.7384, 'longitude' => 7.4246],
            ['name' => 'Moldova', 'code_iso2' => 'MD', 'currency_code' => 'MDL', 'latitude' => 47.4116, 'longitude' => 28.3699],
            ['name' => 'Montenegro', 'code_iso2' => 'ME', 'currency_code' => 'EUR', 'latitude' => 42.7087, 'longitude' => 19.3744],
            ['name' => 'Saint Martin', 'code_iso2' => 'MF', 'currency_code' => 'EUR', 'latitude' => 18.0708, 'longitude' => -63.0501],
            ['name' => 'Madagascar', 'code_iso2' => 'MG', 'currency_code' => 'MGA', 'latitude' => -18.7669, 'longitude' => 46.8691],
            ['name' => 'Marshall Islands', 'code_iso2' => 'MH', 'currency_code' => 'USD', 'latitude' => 7.1315, 'longitude' => 171.1845],
            ['name' => 'Macedonia', 'code_iso2' => 'MK', 'currency_code' => 'MKD', 'latitude' => 41.6086, 'longitude' => 21.7453],
            ['name' => 'Mali', 'code_iso2' => 'ML', 'currency_code' => 'XOF', 'latitude' => 17.5707, 'longitude' => -3.9962],
            ['name' => 'Myanmar', 'code_iso2' => 'MM', 'currency_code' => 'MMK', 'latitude' => 21.9162, 'longitude' => 95.9560],
            ['name' => 'Mongolia', 'code_iso2' => 'MN', 'currency_code' => 'MNT', 'latitude' => 46.8625, 'longitude' => 103.8467],
            ['name' => 'Macao', 'code_iso2' => 'MO', 'currency_code' => 'MOP', 'latitude' => 22.1987, 'longitude' => 113.5439],
            ['name' => 'Northern Mariana Islands', 'code_iso2' => 'MP', 'currency_code' => 'USD', 'latitude' => 15.0979, 'longitude' => 145.6739],
            ['name' => 'Martinique', 'code_iso2' => 'MQ', 'currency_code' => 'EUR', 'latitude' => 14.6415, 'longitude' => -61.0242],
            ['name' => 'Mauritania', 'code_iso2' => 'MR', 'currency_code' => 'MRU', 'latitude' => 21.0079, 'longitude' => -10.9408],
            ['name' => 'Montserrat', 'code_iso2' => 'MS', 'currency_code' => 'XCD', 'latitude' => 16.7425, 'longitude' => -62.1873],
            ['name' => 'Malta', 'code_iso2' => 'MT', 'currency_code' => 'EUR', 'latitude' => 35.9375, 'longitude' => 14.3754],
            ['name' => 'Mauritius', 'code_iso2' => 'MU', 'currency_code' => 'MUR', 'latitude' => -20.3484, 'longitude' => 57.5522],
            ['name' => 'Maldives', 'code_iso2' => 'MV', 'currency_code' => 'MVR', 'latitude' => 3.2028, 'longitude' => 73.2207],
            ['name' => 'Malawi', 'code_iso2' => 'MW', 'currency_code' => 'MWK', 'latitude' => -13.2543, 'longitude' => 34.3015],
            ['name' => 'Mexico', 'code_iso2' => 'MX', 'currency_code' => 'MXN', 'latitude' => 23.6345, 'longitude' => -102.5528],
            ['name' => 'Malaysia', 'code_iso2' => 'MY', 'currency_code' => 'MYR', 'latitude' => 4.2105, 'longitude' => 101.9758],
            ['name' => 'Mozambique', 'code_iso2' => 'MZ', 'currency_code' => 'MZN', 'latitude' => -18.6657, 'longitude' => 35.5296],
            ['name' => 'Namibia', 'code_iso2' => 'NA', 'currency_code' => 'NAD', 'latitude' => -22.9576, 'longitude' => 18.4904],
            ['name' => 'New Caledonia', 'code_iso2' => 'NC', 'currency_code' => 'XPF', 'latitude' => -20.9043, 'longitude' => 165.6180],
            ['name' => 'Niger', 'code_iso2' => 'NE', 'currency_code' => 'XOF', 'latitude' => 17.6078, 'longitude' => 8.0817],
            ['name' => 'Norfolk Island', 'code_iso2' => 'NF', 'currency_code' => 'AUD', 'latitude' => -29.0408, 'longitude' => 167.9547],
            ['name' => 'Nigeria', 'code_iso2' => 'NG', 'currency_code' => 'NGN', 'latitude' => 9.0820, 'longitude' => 8.6753],
            ['name' => 'Nicaragua', 'code_iso2' => 'NI', 'currency_code' => 'NIO', 'latitude' => 12.8654, 'longitude' => -85.2072],
            ['name' => 'Netherlands', 'code_iso2' => 'NL', 'currency_code' => 'EUR', 'latitude' => 52.1326, 'longitude' => 5.2913],
            ['name' => 'Norway', 'code_iso2' => 'NO', 'currency_code' => 'NOK', 'latitude' => 60.4720, 'longitude' => 8.4689],
            ['name' => 'Nepal', 'code_iso2' => 'NP', 'currency_code' => 'NPR', 'latitude' => 28.3949, 'longitude' => 84.1240],
            ['name' => 'Nauru', 'code_iso2' => 'NR', 'currency_code' => 'AUD', 'latitude' => -0.5228, 'longitude' => 166.9315],
            ['name' => 'Niue', 'code_iso2' => 'NU', 'currency_code' => 'NZD', 'latitude' => -19.0544, 'longitude' => -169.8672],
            ['name' => 'New Zealand', 'code_iso2' => 'NZ', 'currency_code' => 'NZD', 'latitude' => -40.9006, 'longitude' => 174.8860],
            ['name' => 'Oman', 'code_iso2' => 'OM', 'currency_code' => 'OMR', 'latitude' => 21.5126, 'longitude' => 55.9233],
            ['name' => 'Panama', 'code_iso2' => 'PA', 'currency_code' => 'PAB', 'latitude' => 8.5380, 'longitude' => -80.7821],
            ['name' => 'Peru', 'code_iso2' => 'PE', 'currency_code' => 'PEN', 'latitude' => -9.1900, 'longitude' => -75.0152],
            ['name' => 'French Polynesia', 'code_iso2' => 'PF', 'currency_code' => 'XPF', 'latitude' => -17.6509, 'longitude' => -149.4068],
            ['name' => 'Papua New Guinea', 'code_iso2' => 'PG', 'currency_code' => 'PGK', 'latitude' => -6.3150, 'longitude' => 143.9555],
            ['name' => 'Philippines', 'code_iso2' => 'PH', 'currency_code' => 'PHP', 'latitude' => 12.8797, 'longitude' => 121.7740],
            ['name' => 'Pakistan', 'code_iso2' => 'PK', 'currency_code' => 'PKR', 'latitude' => 30.3753, 'longitude' => 69.3451],
            ['name' => 'Poland', 'code_iso2' => 'PL', 'currency_code' => 'PLN', 'latitude' => 51.9194, 'longitude' => 19.1451],
            ['name' => 'Saint Pierre and Miquelon', 'code_iso2' => 'PM', 'currency_code' => 'EUR', 'latitude' => 46.8852, 'longitude' => -56.3159],
            ['name' => 'Pitcairn', 'code_iso2' => 'PN', 'currency_code' => 'NZD', 'latitude' => -24.7036, 'longitude' => -127.4393],
            ['name' => 'Puerto Rico', 'code_iso2' => 'PR', 'currency_code' => 'USD', 'latitude' => 18.2208, 'longitude' => -66.5901],
            ['name' => 'Palestine', 'code_iso2' => 'PS', 'currency_code' => 'ILS', 'latitude' => 31.9522, 'longitude' => 35.2332],
            ['name' => 'Portugal', 'code_iso2' => 'PT', 'currency_code' => 'EUR', 'latitude' => 39.3999, 'longitude' => -8.2245],
            ['name' => 'Palau', 'code_iso2' => 'PW', 'currency_code' => 'USD', 'latitude' => 7.5150, 'longitude' => 134.5825],
            ['name' => 'Paraguay', 'code_iso2' => 'PY', 'currency_code' => 'PYG', 'latitude' => -23.4425, 'longitude' => -58.4438],
            ['name' => 'Qatar', 'code_iso2' => 'QA', 'currency_code' => 'QAR', 'latitude' => 25.3548, 'longitude' => 51.1839],
            ['name' => 'Reunion', 'code_iso2' => 'RE', 'currency_code' => 'EUR', 'latitude' => -21.1151, 'longitude' => 55.5364],
            ['name' => 'Romania', 'code_iso2' => 'RO', 'currency_code' => 'RON', 'latitude' => 45.9432, 'longitude' => 24.9668],
            ['name' => 'Serbia', 'code_iso2' => 'RS', 'currency_code' => 'RSD', 'latitude' => 44.0165, 'longitude' => 21.0059],
            ['name' => 'Russia', 'code_iso2' => 'RU', 'currency_code' => 'RUB', 'latitude' => 61.5240, 'longitude' => 105.3188],
            ['name' => 'Rwanda', 'code_iso2' => 'RW', 'currency_code' => 'RWF', 'latitude' => -1.9403, 'longitude' => 29.8739],
            ['name' => 'Saudi Arabia', 'code_iso2' => 'SA', 'currency_code' => 'SAR', 'latitude' => 23.8859, 'longitude' => 45.0792],
            ['name' => 'Solomon Islands', 'code_iso2' => 'SB', 'currency_code' => 'SBD', 'latitude' => -9.6457, 'longitude' => 160.1562],
            ['name' => 'Seychelles', 'code_iso2' => 'SC', 'currency_code' => 'SCR', 'latitude' => -4.6796, 'longitude' => 55.4920],
            ['name' => 'Sudan', 'code_iso2' => 'SD', 'currency_code' => 'SDG', 'latitude' => 12.8628, 'longitude' => 30.2176],
            ['name' => 'Sweden', 'code_iso2' => 'SE', 'currency_code' => 'SEK', 'latitude' => 60.1282, 'longitude' => 18.6435],
            ['name' => 'Singapore', 'code_iso2' => 'SG', 'currency_code' => 'SGD', 'latitude' => 1.3521, 'longitude' => 103.8198],
            ['name' => 'Saint Helena', 'code_iso2' => 'SH', 'currency_code' => 'SHP', 'latitude' => -24.1435, 'longitude' => -10.0248],
            ['name' => 'Slovenia', 'code_iso2' => 'SI', 'currency_code' => 'EUR', 'latitude' => 46.1512, 'longitude' => 14.9955],
            ['name' => 'Svalbard', 'code_iso2' => 'SJ', 'currency_code' => 'NOK', 'latitude' => 77.5536, 'longitude' => 23.6703],
            ['name' => 'Slovakia', 'code_iso2' => 'SK', 'currency_code' => 'EUR', 'latitude' => 48.6690, 'longitude' => 19.6990],
            ['name' => 'Sierra Leone', 'code_iso2' => 'SL', 'currency_code' => 'SLE', 'latitude' => 8.4606, 'longitude' => -11.7799],
            ['name' => 'San Marino', 'code_iso2' => 'SM', 'currency_code' => 'EUR', 'latitude' => 43.9424, 'longitude' => 12.4578],
            ['name' => 'Senegal', 'code_iso2' => 'SN', 'currency_code' => 'XOF', 'latitude' => 14.4974, 'longitude' => -14.4524],
            ['name' => 'Somalia', 'code_iso2' => 'SO', 'currency_code' => 'SOS', 'latitude' => 5.1521, 'longitude' => 46.1996],
            ['name' => 'Suriname', 'code_iso2' => 'SR', 'currency_code' => 'SRD', 'latitude' => 3.9193, 'longitude' => -56.0278],
            ['name' => 'South Sudan', 'code_iso2' => 'SS', 'currency_code' => 'SSP', 'latitude' => 6.8770, 'longitude' => 31.3070],
            ['name' => 'Sao Tome and Principe', 'code_iso2' => 'ST', 'currency_code' => 'STN', 'latitude' => 0.1864, 'longitude' => 6.6131],
            ['name' => 'El Salvador', 'code_iso2' => 'SV', 'currency_code' => 'USD', 'latitude' => 13.7942, 'longitude' => -88.8965],
            ['name' => 'Sint Maarten', 'code_iso2' => 'SX', 'currency_code' => 'ANG', 'latitude' => 18.0425, 'longitude' => -63.0548],
            ['name' => 'Syria', 'code_iso2' => 'SY', 'currency_code' => 'SYP', 'latitude' => 34.8021, 'longitude' => 38.9968],
            ['name' => 'Swaziland', 'code_iso2' => 'SZ', 'currency_code' => 'SZL', 'latitude' => -26.5225, 'longitude' => 31.4659],
            ['name' => 'Turks and Caicos Islands', 'code_iso2' => 'TC', 'currency_code' => 'USD', 'latitude' => 21.6940, 'longitude' => -71.7979],
            ['name' => 'Chad', 'code_iso2' => 'TD', 'currency_code' => 'XAF', 'latitude' => 15.4542, 'longitude' => 18.7322],
            ['name' => 'French Southern Territories', 'code_iso2' => 'TF', 'currency_code' => 'EUR', 'latitude' => -49.2800, 'longitude' => 69.3600],
            ['name' => 'Togo', 'code_iso2' => 'TG', 'currency_code' => 'XOF', 'latitude' => 8.6195, 'longitude' => 0.8248],
            ['name' => 'Thailand', 'code_iso2' => 'TH', 'currency_code' => 'THB', 'latitude' => 15.8700, 'longitude' => 100.9925],
            ['name' => 'Tajikistan', 'code_iso2' => 'TJ', 'currency_code' => 'TJS', 'latitude' => 38.8610, 'longitude' => 71.2761],
            ['name' => 'Tokelau', 'code_iso2' => 'TK', 'currency_code' => 'NZD', 'latitude' => -9.2002, 'longitude' => -171.8484],
            ['name' => 'East Timor', 'code_iso2' => 'TL', 'currency_code' => 'USD', 'latitude' => -8.8742, 'longitude' => 125.7275],
            ['name' => 'Turkmenistan', 'code_iso2' => 'TM', 'currency_code' => 'TMT', 'latitude' => 38.9697, 'longitude' => 59.5563],
            ['name' => 'Tunisia', 'code_iso2' => 'TN', 'currency_code' => 'TND', 'latitude' => 33.8869, 'longitude' => 9.5375],
            ['name' => 'Tonga', 'code_iso2' => 'TO', 'currency_code' => 'TOP', 'latitude' => -21.1789, 'longitude' => -175.1982],
            ['name' => 'Turkey', 'code_iso2' => 'TR', 'currency_code' => 'TRY', 'latitude' => 38.9637, 'longitude' => 35.2433],
            ['name' => 'Trinidad and Tobago', 'code_iso2' => 'TT', 'currency_code' => 'TTD', 'latitude' => 10.6918, 'longitude' => -61.2225],
            ['name' => 'Tuvalu', 'code_iso2' => 'TV', 'currency_code' => 'AUD', 'latitude' => -7.1095, 'longitude' => 177.6493],
            ['name' => 'Taiwan', 'code_iso2' => 'TW', 'currency_code' => 'TWD', 'latitude' => 23.6978, 'longitude' => 120.9605],
            ['name' => 'Tanzania', 'code_iso2' => 'TZ', 'currency_code' => 'TZS', 'latitude' => -6.3690, 'longitude' => 34.8888],
            ['name' => 'Ukraine', 'code_iso2' => 'UA', 'currency_code' => 'UAH', 'latitude' => 48.3794, 'longitude' => 31.1656],
            ['name' => 'Uganda', 'code_iso2' => 'UG', 'currency_code' => 'UGX', 'latitude' => 1.3733, 'longitude' => 32.2903],
            ['name' => 'United States', 'code_iso2' => 'US', 'currency_code' => 'USD', 'latitude' => 37.0902, 'longitude' => -95.7129],
            ['name' => 'Uruguay', 'code_iso2' => 'UY', 'currency_code' => 'UYU', 'latitude' => -32.5228, 'longitude' => -55.7658],
            ['name' => 'Uzbekistan', 'code_iso2' => 'UZ', 'currency_code' => 'UZS', 'latitude' => 41.3775, 'longitude' => 64.5853],
            ['name' => 'Vatican', 'code_iso2' => 'VA', 'currency_code' => 'EUR', 'latitude' => 41.9029, 'longitude' => 12.4534],
            ['name' => 'Saint Vincent and the Grenadines', 'code_iso2' => 'VC', 'currency_code' => 'XCD', 'latitude' => 12.9843, 'longitude' => -61.2872],
            ['name' => 'Venezuela', 'code_iso2' => 'VE', 'currency_code' => 'VES', 'latitude' => 6.4238, 'longitude' => -66.5897],
            ['name' => 'British Virgin Islands', 'code_iso2' => 'VG', 'currency_code' => 'USD', 'latitude' => 18.4207, 'longitude' => -64.6399],
            ['name' => 'U.S. Virgin Islands', 'code_iso2' => 'VI', 'currency_code' => 'USD', 'latitude' => 18.3358, 'longitude' => -64.8963],
            ['name' => 'Vietnam', 'code_iso2' => 'VN', 'currency_code' => 'VND', 'latitude' => 14.0583, 'longitude' => 108.2772],
            ['name' => 'Vanuatu', 'code_iso2' => 'VU', 'currency_code' => 'VUV', 'latitude' => -15.3767, 'longitude' => 166.9592],
            ['name' => 'Wallis and Futuna', 'code_iso2' => 'WF', 'currency_code' => 'XPF', 'latitude' => -13.7687, 'longitude' => -177.1560],
            ['name' => 'Samoa', 'code_iso2' => 'WS', 'currency_code' => 'WST', 'latitude' => -13.7590, 'longitude' => -172.1046],
            ['name' => 'Yemen', 'code_iso2' => 'YE', 'currency_code' => 'YER', 'latitude' => 15.5527, 'longitude' => 48.5164],
            ['name' => 'Mayotte', 'code_iso2' => 'YT', 'currency_code' => 'EUR', 'latitude' => -12.8275, 'longitude' => 45.1662],
            ['name' => 'South Africa', 'code_iso2' => 'ZA', 'currency_code' => 'ZAR', 'latitude' => -30.5595, 'longitude' => 22.9375],
            ['name' => 'Zambia', 'code_iso2' => 'ZM', 'currency_code' => 'ZMW', 'latitude' => -13.1339, 'longitude' => 27.8493],
            ['name' => 'Zimbabwe', 'code_iso2' => 'ZW', 'currency_code' => 'ZWG', 'latitude' => -19.0154, 'longitude' => 29.1549]
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }

        // 2. Isi Kamus Kata Sentimen Lexicon
        $positives = ['growth', 'increase', 'profit', 'stable', 'improve', 'safe', 'good', 'success', 'boom'];
        foreach ($positives as $word) {
            WordDictionary::create(['word' => $word, 'type' => 'positive']);
        }

        $negatives = ['war', 'crisis', 'inflation', 'delay', 'disaster', 'conflict', 'drop', 'risk', 'strike'];
        foreach ($negatives as $word) {
            WordDictionary::create(['word' => $word, 'type' => 'negative']);
        }
    }
}