@extends('layouts.app')
@section('content')
<style>
    .compare-page{max-width:1540px;margin:auto;color:#eef5ff}.compare-head{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;margin-bottom:20px}.compare-kicker{color:#35e6b1;font-size:.69rem;font-weight:800;letter-spacing:.22em;text-transform:uppercase}.compare-head h1{font-size:2.25rem;font-weight:850;letter-spacing:-.04em;margin:7px 0}.compare-head p{color:#8fa0b7;margin:0;font-size:.84rem}.method-pill{padding:9px 14px;border:1px solid #2b4058;border-radius:99px;background:#0d1725;color:#aabbd0;font-size:.68rem}
    .selector-shell{display:grid;grid-template-columns:1fr 62px 1fr;gap:12px;align-items:center;padding:15px;background:#0d1725;border:1px solid #26384e;border-radius:18px;margin-bottom:16px}.select-field label{display:block;color:#7f91a9;font-size:.62rem;text-transform:uppercase;letter-spacing:.11em;margin:0 0 7px}.select-field select{width:100%;height:50px;border:1px solid #2c4059;background:#09131f;color:#fff;border-radius:12px;padding:0 14px;outline:none}.select-field select:focus{border-color:#35e6b1}.versus{width:51px;height:51px;border-radius:50%;display:grid;place-items:center;margin:auto;background:linear-gradient(135deg,#35e6b1,#37c8ff);color:#06131a;font-size:.72rem;font-weight:900;box-shadow:0 0 28px rgba(53,230,177,.18)}
    .country-cards{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}.country-card{position:relative;overflow:hidden;padding:21px;background:linear-gradient(145deg,#111e30,#0b1421);border:1px solid #283a51;border-radius:19px}.country-card:after{content:"";position:absolute;width:180px;height:180px;border-radius:50%;right:-65px;top:-85px;background:var(--accent);filter:blur(90px);opacity:.16}.country-top{position:relative;z-index:1;display:flex;gap:14px;align-items:center}.country-flag{width:74px;height:50px;object-fit:cover;border-radius:10px;border:1px solid #405068;background:#fff}.country-title h2{font-size:1.18rem;font-weight:850;margin:0}.country-title p{color:#8294ac;font-size:.68rem;margin:4px 0 0}.risk-summary{position:relative;z-index:1;display:flex;justify-content:space-between;align-items:center;margin-top:18px;padding-top:16px;border-top:1px solid #24344a}.risk-number strong{display:block;font-size:1.75rem}.risk-number span{font-size:.63rem;color:#7c8ea7}.risk-status{padding:6px 10px;border-radius:99px;font-size:.64rem;font-weight:800}.low{background:#123c30;color:#42eab4}.medium{background:#443619;color:#ffd05a}.high{background:#421c29;color:#ff718a}.unknown{background:#1c2a3e;color:#8da1bb}.country-facts{position:relative;z-index:1;display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:14px}.fact{padding:10px;background:#09131f;border:1px solid #1f3046;border-radius:10px}.fact span{display:block;color:#7588a2;font-size:.6rem;margin-bottom:4px}.fact strong{font-size:.72rem}
    .comparison-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px}.compare-panel{background:#0d1725;border:1px solid #26384e;border-radius:19px;padding:20px;min-width:0}.panel-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:17px}.panel-head h2{font-size:.94rem;font-weight:800;margin:0}.panel-head span{color:#74879f;font-size:.64rem}.metric-list{display:flex;flex-direction:column}.metric-row{display:grid;grid-template-columns:1fr 130px 90px 130px;gap:10px;align-items:center;padding:14px 0;border-bottom:1px solid #1e2d42}.metric-row:last-child{border:0}.metric-name{font-size:.72rem;color:#8698af}.metric-value{font-size:.76rem;font-weight:750}.metric-value.right{text-align:right}.delta{text-align:center;font-size:.61rem;color:#788ba3}.winner{color:#42e5b2}.chart-wrap{height:310px}.insight{margin-top:14px;padding:13px;border:1px solid #29405a;border-radius:12px;background:#101d2e;color:#8fa2ba;font-size:.7rem;line-height:1.55}.insight strong{color:#42e5b2}.loading{opacity:.48;pointer-events:none}.error-box{color:#ff7b91;font-size:.72rem;margin-bottom:12px}
    @media(max-width:1050px){.comparison-grid{grid-template-columns:1fr}.country-facts{grid-template-columns:1fr 1fr}}@media(max-width:700px){.compare-head{align-items:flex-start;flex-direction:column}.selector-shell{grid-template-columns:1fr}.versus{width:38px;height:38px}.country-cards{grid-template-columns:1fr}.metric-row{grid-template-columns:1fr 1fr}.metric-name{grid-column:span 2}.delta{display:none}}
</style>
<div class="compare-page" id="compareApp">
    <header class="compare-head"><div><div class="compare-kicker">Strategic Benchmarking</div><h1>Country Comparison Studio</h1><p>Bandingkan kekuatan ekonomi dan eksposur risiko supply chain secara berdampingan.</p></div><div class="method-pill">Risk model · Weather 30% · News 40%</div></header>
    <section class="selector-shell"><div class="select-field"><label>Negara pembanding A</label><select id="left"></select></div><div class="versus">VS</div><div class="select-field"><label>Negara pembanding B</label><select id="right"></select></div></section><div id="message" class="error-box"></div>
    <section class="country-cards"><article class="country-card" id="leftCard" style="--accent:#35e6b1"></article><article class="country-card" id="rightCard" style="--accent:#9878ff"></article></section>
    <section class="comparison-grid"><article class="compare-panel"><div class="panel-head"><h2>Executive Metric Comparison</h2><span>Snapshot terbaru database</span></div><div class="metric-list" id="metrics"></div><div class="insight" id="insight"></div></article><article class="compare-panel"><div class="panel-head"><h2>Risk Exposure Radar</h2><span>Semakin rendah semakin baik</span></div><div class="chart-wrap"><canvas id="riskRadar"></canvas></div></article></section>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){
 let countries=[],chart,requestId=0;const app=document.getElementById('compareApp'),left=document.getElementById('left'),right=document.getElementById('right'),message=document.getElementById('message');
 const num=v=>Number(v||0),compact=v=>v?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(num(v)):'—',pct=v=>v!==null&&v!==undefined?num(v).toFixed(2)+'%':'—';
 const riskClass=s=>(s||'').toLowerCase().startsWith('low')?'low':((s||'').toLowerCase().startsWith('medium')?'medium':((s||'').toLowerCase().startsWith('high')?'high':'unknown'));
 function card(c){const r=c.risk||{};return `<div class="country-top"><img class="country-flag" src="https://flagcdn.com/w160/${c.code_iso2.toLowerCase()}.png" onerror="this.style.visibility='hidden'"><div class="country-title"><h2>${c.name}</h2><p>${c.region||'Wilayah belum tersedia'} · ${c.code_iso2}</p></div></div><div class="country-facts"><div class="fact"><span>GDP</span><strong>${compact(c.gdp)}</strong></div><div class="fact"><span>Populasi</span><strong>${compact(c.population)}</strong></div><div class="fact"><span>Mata uang</span><strong>${c.currency_code||'—'}</strong></div></div><div class="risk-summary"><div class="risk-number"><strong>${r.total_score??'—'}</strong><span>COMPOSITE RISK</span></div><span class="risk-status ${riskClass(r.status)}">${r.status||'Belum dinilai'}</span></div>`}
 function metric(name,a,b,lowerBetter=false,format=v=>v){const av=num(a),bv=num(b),equal=av===bv,leftWin=lowerBetter?av<bv:av>bv,rightWin=lowerBetter?bv<av:bv>av,delta=Math.abs(av-bv);return `<div class="metric-row"><span class="metric-name">${name}</span><span class="metric-value ${leftWin&&!equal?'winner':''}">${format(a)}</span><span class="delta">Δ ${format(delta)}</span><span class="metric-value right ${rightWin&&!equal?'winner':''}">${format(b)}</span></div>`}
 async function compare(){const id=++requestId;if(!left.value||!right.value)return;app.classList.add('loading');message.textContent='';try{const responses=await Promise.all([left.value,right.value].map(code=>fetch(`/api/countries/${code}`).then(r=>{if(!r.ok)throw new Error('Data negara gagal dimuat');return r.json()})));if(id!==requestId)return;const [a,b]=responses.map(r=>r.data);document.getElementById('leftCard').innerHTML=card(a);document.getElementById('rightCard').innerHTML=card(b);document.getElementById('metrics').innerHTML=metric('Gross Domestic Product',a.gdp,b.gdp,false,compact)+metric('Population',a.population,b.population,false,compact)+metric('Inflation Rate',a.inflation_rate,b.inflation_rate,true,pct)+metric('Composite Risk',a.risk?.total_score,b.risk?.total_score,true,v=>num(v).toFixed(1));const ar=num(a.risk?.total_score),br=num(b.risk?.total_score),sa=ar<=br?a:b,sb=ar<=br?b:a;document.getElementById('insight').innerHTML=`<strong>${sa.name}</strong> memiliki profil risiko lebih rendah ${Math.abs(ar-br).toFixed(1)} poin dibanding ${sb.name}. Gunakan indikator ekonomi dan breakdown risiko sebagai bahan analisis, bukan satu-satunya dasar keputusan.`;chart?.destroy();chart=new Chart(document.getElementById('riskRadar'),{type:'radar',data:{labels:['Cuaca','Inflasi','Kurs','Berita'],datasets:[{label:a.name,data:[a.risk?.weather_risk||0,a.risk?.inflation_risk||0,a.risk?.currency_risk||0,a.risk?.news_risk||0],borderColor:'#35e6b1',backgroundColor:'rgba(53,230,177,.15)',pointBackgroundColor:'#35e6b1'},{label:b.name,data:[b.risk?.weather_risk||0,b.risk?.inflation_risk||0,b.risk?.currency_risk||0,b.risk?.news_risk||0],borderColor:'#9878ff',backgroundColor:'rgba(152,120,255,.14)',pointBackgroundColor:'#9878ff'}]},options:{responsive:true,maintainAspectRatio:false,scales:{r:{beginAtZero:true,max:100,grid:{color:'rgba(130,150,175,.16)'},angleLines:{color:'rgba(130,150,175,.16)'},pointLabels:{color:'#a9bad0'},ticks:{display:false}}},plugins:{legend:{labels:{color:'#a9bad0',usePointStyle:true}}}}})}catch(e){if(id===requestId)message.textContent=e.message+'. Coba pilih kembali negara.'}finally{if(id===requestId)app.classList.remove('loading')}}
 async function load(){const response=await fetch('/api/countries'),json=await response.json();countries=(json.data||[]).sort((a,b)=>a.name.localeCompare(b.name));const options=countries.map(c=>`<option value="${c.code_iso2}">${c.code_iso2} — ${c.name}</option>`).join('');left.innerHTML=right.innerHTML=options;left.value=countries.some(c=>c.code_iso2==='ID')?'ID':countries[0]?.code_iso2;right.value=countries.some(c=>c.code_iso2==='DE')?'DE':countries[1]?.code_iso2;left.addEventListener('change',compare);right.addEventListener('change',compare);compare()}load().catch(()=>message.textContent='Data belum tersedia. Jalankan sinkronisasi negara terlebih dahulu.');
});
</script>
@endsection
