@extends('layouts.app')
@section('content')
@php
    $validCurrencies = collect($currencies)->whereNotNull('rate_value');
    $uniqueCurrencies = $validCurrencies->unique('curr_code')->sortBy('curr_code')->values();
@endphp
<style>
    .fx-page{max-width:1540px;margin:auto;color:#eef5ff}.fx-header{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:21px}.fx-kicker{color:#35e6b1;font-size:.69rem;letter-spacing:.22em;font-weight:800;text-transform:uppercase}.fx-header h1{font-size:2.25rem;font-weight:850;letter-spacing:-.04em;margin:7px 0}.fx-header p{color:#8fa0b7;margin:0;font-size:.84rem}.market-open{padding:9px 14px;border:1px solid #29415a;border-radius:99px;background:#0d1725;color:#b7c6d9;font-size:.69rem}.market-open i{display:inline-block;width:8px;height:8px;background:#35e6b1;border-radius:50%;box-shadow:0 0 13px #35e6b1;margin-right:8px}
    .fx-overview{display:grid;grid-template-columns:1.55fr 1fr;gap:16px;margin-bottom:17px}.converter{position:relative;overflow:hidden;padding:25px;background:linear-gradient(135deg,#13243a,#0b1422 60%,#181433);border:1px solid #2c4059;border-radius:21px}.converter:after{content:"";position:absolute;width:250px;height:250px;border-radius:50%;right:-80px;top:-110px;background:#7157ff;filter:blur(90px);opacity:.2}.panel-title{position:relative;z-index:1;display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.panel-title h2{font-size:1rem;font-weight:800;margin:0}.panel-title span{font-size:.65rem;color:#7f91aa}.convert-grid{position:relative;z-index:1;display:grid;grid-template-columns:1fr 135px 42px 1fr 135px;gap:9px;align-items:end}.field label{display:block;color:#8092aa;font-size:.62rem;margin:0 0 7px;text-transform:uppercase;letter-spacing:.1em}.field input,.field select{width:100%;height:48px;background:#08121f;border:1px solid #2b3e58;border-radius:11px;color:#fff;padding:0 13px;outline:none}.field input:focus,.field select:focus{border-color:#35e6b1}.swap{height:48px;border:1px solid #344a65;border-radius:11px;background:#17263a;color:#3ee5b2;font-size:1rem}.conversion-result{position:relative;z-index:1;margin-top:19px;padding-top:17px;border-top:1px solid #2a3b50}.conversion-result span{color:#8496ae;font-size:.68rem}.conversion-result strong{display:block;font-size:1.65rem;margin-top:4px}.market-info{display:grid;grid-template-columns:1fr 1fr;gap:12px}.market-stat{padding:18px;background:linear-gradient(145deg,#111c2d,#0b1421);border:1px solid #25374e;border-radius:17px}.market-stat span{font-size:.66rem;color:#8192aa;display:block}.market-stat strong{display:block;font-size:1.35rem;margin:6px 0}.market-stat small{color:#35e6b1;font-size:.61rem}.market-stat.wide{grid-column:span 2}.market-stat.wide strong{font-size:.9rem;line-height:1.4}
    .major-section{margin-bottom:17px}.section-head{display:flex;justify-content:space-between;align-items:center;margin:0 0 11px}.section-head h2{font-size:1rem;font-weight:800}.section-head span{color:#7688a1;font-size:.67rem}.rate-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.rate-card{padding:15px;background:#0e1928;border:1px solid #24364c;border-radius:15px;transition:.2s}.rate-card:hover{transform:translateY(-2px);border-color:#3d566f}.rate-top{display:flex;justify-content:space-between;align-items:center}.rate-code{font-weight:850}.rate-symbol{width:31px;height:31px;display:grid;place-items:center;background:#17273d;border-radius:9px;color:#43dfb1}.rate-card strong{font-size:1.05rem;display:block;margin-top:14px}.rate-card small{color:#788aa3;font-size:.62rem}
    .ledger{border:1px solid #26384e;background:#0d1725;border-radius:19px;overflow:hidden}.ledger-tools{display:grid;grid-template-columns:1fr 220px auto;gap:10px;padding:15px;border-bottom:1px solid #22334a}.ledger-tools input,.ledger-tools select{height:43px;border:1px solid #2a3d56;background:#09121f;color:#fff;border-radius:10px;padding:0 13px;outline:none}.ledger-tools button{border:0;background:#35e6b1;color:#06140f;border-radius:10px;padding:0 18px;font-weight:800}.ledger-count{display:flex;justify-content:space-between;padding:14px 17px;color:#8596ad;font-size:.68rem;background:#101c2d}.currency-table{width:100%;border-collapse:collapse}.currency-table th{padding:13px 16px;text-align:left;font-size:.63rem;color:#7689a3;text-transform:uppercase;letter-spacing:.1em}.currency-table td{padding:13px 16px;border-top:1px solid #1d2b40;font-size:.74rem}.currency-table tbody tr:hover{background:#122035}.country-id{display:flex;align-items:center;gap:11px}.country-id img{width:34px;height:23px;object-fit:cover;border-radius:5px;background:#fff}.country-id strong{display:block}.country-id span{display:block;color:#73869f;font-size:.61rem;margin-top:2px}.code-pill{display:inline-flex;padding:4px 8px;border-radius:7px;background:#17263b;color:#9bb2cf;font-family:ui-monospace,monospace;font-size:.64rem}.rate-value{font-family:ui-monospace,monospace;color:#f1f6fc;font-weight:750}.copy-rate{border:1px solid #2b4059;background:#111e30;color:#41dcae;border-radius:8px;padding:6px 9px;font-size:.62rem}.no-rate{color:#697b93}.table-wrap{max-height:620px;overflow:auto}.table-wrap thead{position:sticky;top:0;background:#0d1725;z-index:2}
    @media(max-width:1100px){.fx-overview{grid-template-columns:1fr}.rate-strip{grid-template-columns:1fr 1fr}.convert-grid{grid-template-columns:1fr 120px}.swap{display:none}.ledger{overflow:auto}.currency-table{min-width:850px}}@media(max-width:650px){.fx-header{align-items:flex-start;flex-direction:column}.fx-header h1{font-size:1.75rem}.convert-grid,.market-info,.ledger-tools{grid-template-columns:1fr}.market-stat.wide{grid-column:auto}.rate-strip{grid-template-columns:1fr}}
</style>
<div class="fx-page">
    <header class="fx-header"><div><div class="fx-kicker">Global FX Intelligence</div><h1>Currency Operations Center</h1><p>Pantau dan konversikan kurs global berbasis USD dengan data pasar terkini.</p></div><div class="market-open"><i></i>Exchange feed online</div></header>

    <section class="fx-overview">
        <article class="converter"><div class="panel-title"><h2>Quick Currency Converter</h2><span>Base rate · USD</span></div><div class="convert-grid"><div class="field"><label>Jumlah</label><input id="fromAmount" type="number" value="1" min="0" step="any"></div><div class="field"><label>Dari</label><select id="fromCurrency">@foreach($uniqueCurrencies as $c)<option value="{{ $c['rate_value'] }}" data-code="{{ $c['curr_code'] }}" @selected($c['curr_code']==='USD')>{{ $c['curr_code'] }}</option>@endforeach</select></div><button class="swap" id="swapCurrency" type="button">⇄</button><div class="field"><label>Hasil</label><input id="toAmount" readonly></div><div class="field"><label>Ke</label><select id="toCurrency">@foreach($uniqueCurrencies as $c)<option value="{{ $c['rate_value'] }}" data-code="{{ $c['curr_code'] }}" @selected($c['curr_code']==='IDR')>{{ $c['curr_code'] }}</option>@endforeach</select></div></div><div class="conversion-result"><span id="conversionLabel">Live conversion</span><strong id="conversionBig">—</strong></div></article>
        <aside class="market-info"><article class="market-stat"><span>Negara & teritori</span><strong>{{ count($currencies) }}</strong><small>Global coverage</small></article><article class="market-stat"><span>Mata uang tersedia</span><strong>{{ $availableRates }}</strong><small>API rate pairs</small></article><article class="market-stat wide"><span>Pembaruan pasar terakhir</span><strong>{{ $updatedAt ? \Carbon\Carbon::parse($updatedAt)->setTimezone('Asia/Jakarta')->format('d M Y · H:i') : 'Menunggu koneksi API' }}</strong><small>Zona waktu Jakarta (WIB)</small></article></aside>
    </section>

    <section class="major-section"><div class="section-head"><h2>Major Currency Board</h2><span>1 USD terhadap mata uang utama</span></div><div class="rate-strip">@foreach($featured as $rate)<article class="rate-card"><div class="rate-top"><span class="rate-code">{{ $rate['code'] }}</span><span class="rate-symbol">{{ $rate['symbol'] }}</span></div><strong>{{ $rate['rate'] ? number_format($rate['rate'],4) : 'N/A' }}</strong><small>{{ $rate['name'] }}</small></article>@endforeach</div></section>

    <section class="ledger"><div class="ledger-tools"><input id="searchInput" placeholder="Cari negara, wilayah, atau kode mata uang..."><select id="regionSelect"><option value="all">Semua wilayah</option>@foreach(collect($currencies)->pluck('region')->unique()->sort() as $region)<option value="{{ $region }}">{{ $region }}</option>@endforeach</select><button type="button" onclick="window.location.reload()">↻ Perbarui kurs</button></div><div class="ledger-count"><span>Global Exchange Ledger</span><span><strong id="rowCount">{{ count($currencies) }}</strong> negara ditampilkan</span></div><div class="table-wrap"><table class="currency-table"><thead><tr><th>Negara</th><th>Mata uang</th><th>Kode</th><th>Simbol</th><th>Nilai per 1 USD</th><th>Aksi</th></tr></thead><tbody>@foreach($currencies as $c)<tr class="currency-row" data-search="{{ strtolower($c['name'].' '.$c['curr_name'].' '.$c['curr_code']) }}" data-region="{{ $c['region'] }}"><td><div class="country-id"><img src="https://flagcdn.com/w80/{{ $c['code'] }}.png" alt="" onerror="this.style.display='none'"><div><strong>{{ $c['name'] }}</strong><span>{{ $c['region'] }}</span></div></div></td><td>{{ $c['curr_name'] }}</td><td><span class="code-pill">{{ $c['curr_code'] }}</span></td><td>{{ $c['symbol'] }}</td><td>@if($c['rate_value'] !== null)<span class="rate-value">{{ number_format($c['rate_value'],4) }}</span>@else<span class="no-rate">Tidak tersedia</span>@endif</td><td>@if($c['rate_value'] !== null)<button class="copy-rate" data-copy="1 USD = {{ number_format($c['rate_value'],4) }} {{ $c['curr_code'] }}">Salin kurs</button>@else—@endif</td></tr>@endforeach</tbody></table></div></section>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){
 const amount=document.getElementById('fromAmount'),from=document.getElementById('fromCurrency'),to=document.getElementById('toCurrency'),result=document.getElementById('toAmount'),big=document.getElementById('conversionBig'),label=document.getElementById('conversionLabel');
 function convert(){const value=(parseFloat(amount.value)||0)/parseFloat(from.value)*parseFloat(to.value),fromCode=from.options[from.selectedIndex]?.dataset.code,toCode=to.options[to.selectedIndex]?.dataset.code;result.value=new Intl.NumberFormat('id-ID',{maximumFractionDigits:4}).format(value);big.textContent=result.value+' '+toCode;label.textContent=(amount.value||0)+' '+fromCode+' setara dengan'}
 [amount,from,to].forEach(el=>el.addEventListener('input',convert));document.getElementById('swapCurrency').addEventListener('click',()=>{const a=from.selectedIndex;from.selectedIndex=to.selectedIndex;to.selectedIndex=a;convert()});convert();
 const search=document.getElementById('searchInput'),region=document.getElementById('regionSelect'),rows=[...document.querySelectorAll('.currency-row')];function filter(){let count=0;rows.forEach(row=>{const show=row.dataset.search.includes(search.value.toLowerCase())&&(region.value==='all'||row.dataset.region===region.value);row.style.display=show?'':'none';if(show)count++});document.getElementById('rowCount').textContent=count}search.addEventListener('input',filter);region.addEventListener('change',filter);
 document.querySelectorAll('.copy-rate').forEach(button=>button.addEventListener('click',async()=>{await navigator.clipboard.writeText(button.dataset.copy);const old=button.textContent;button.textContent='Tersalin ✓';setTimeout(()=>button.textContent=old,1200)}));
});
</script>
@endsection
